spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: csucoderlee
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&amp;characterEncoding=utf-8

#  http:
#    encoding:
#      charset: utf-8
#      force: true
#      force-request: true
#      force-response: true
